log_level: INFO
memory_threshold_percent: 70
moving_window_days: 5
orca_binarize: true
output_format: parquet
paths:
  diario_dir: D:/Projects/visualizer-tuis/data/raw/CIS/Diario
  medidores: data/refined/CIS/MEDIDORES.parquet
  mixed_output: data/trusted/mixed
  municipio_daily_output: data/trusted/municipio_daily
  orca_enriched: data/trusted/ORCA/Dados_Comunicacao_com_datas.csv
  orca_raw: data/raw/ORCA/Dados_Comunicacao.parquet
  orca_ref_date: data/trusted/CIS/Data_Referencia.csv
  sanplat_enriched: data/trusted/SANPLAT/Dados_Comunicacao_SANPLAT_com_datas.csv
  sanplat_ref_date: data/trusted/SANPLAT/Data_Referencia_2.csv
  sanplat_refined: data/refined/SANPLAT/Dados_Comunicacao_SANPLAT.csv
sink_queue_limit: 3
sink_retry_attempts: 3
target_month: 2026-02
